### ISSUE TITLE
Adding climbing

### ISSUE THREAD

**Issue by Seanmclem** [talkol/spiderman#8]
Web slinging is great and fun until you hit a wall. Sometimes it would be nice to grab onto the wall or climb a little bit more and get on the roof or something. 

There could be a button that you hold to climb or stick to the wall. 

Maybe eventually basic locomotion would be a great fun addition. For moving across the roof. 

Got my oculus quest today. I'm a professional js developer looking to branch into web VR.

I'm probably going to try adding this ability, unless someone is already working on it. Is there a better way to avoid duplicating efforts than a GitHub issue? Genuinely asking.

**Comment by CheezeFPV** [comment]
This.... Would be epic

**Comment by talkol** [comment]
Feel free, it will be very cool

**Comment by CheezeFPV** [comment]
Every time I start getting close to a wall, I'm always thinking to myself... How cool would it be to be able to land on a wall and run for a bit, then jump off and continue on doing whatever.

one of my favorite games is Titanfall, and it's because of that mobility where you can just keep going no matter what surface you're running on. It's like parkour heaven.

Spider-Man is all about parkour. 🤓

I like the idea of being able to press a button and either stick to a wall, or to run on the wall.

**Comment by Seanmclem** [comment]
My Quest was supposed to arrive the day of my post, but was late and eventually got canceled. I have a new order arriving in 2 or 3 weeks. So a bit of a delay, but I see chrome and Firefox have WebXR emulator extensions. So I'll use that to get started testing some basic changes

**Comment by HypNotikZ** [comment]
Update when you get your headset plz I would really look forward to seeing some smart minds working on these types of things

**Comment by Aem1024** [comment]
how is it going?
